config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/recipes', to:'pages#recipes'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :ramen_recipes
  resources :component_recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/component_recipe.rb
class ComponentRecipe < ApplicationRecord
  belongs_to :user
   has_and_belongs_to_many :ramen_recipes

  validates :component, :description, :ingredients, :directions, presence: true
end

app/models/ramen_recipe.rb
class RamenRecipe < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :component_recipes

  validates :description, :ramen_type, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/component_recipes_controller.rb
class ComponentRecipesController < ApplicationController
  before_action :set_params, only: %i[create update]
  before_action :set_component_recipes, only: %i[show edit update destroy]

  def index
    @component_recipes = ComponentRecipe.all
  end

  def show
  end

  def new
    @component_recipes = ComponentRecipe.new
  end

  def create
    @component_recipes = ComponentRecipe.new(set_params)
    @component_recipes.user = current_user
    if @component_recipes.save
      redirect_to Component_recipes_path(@component_recipes)
    else
      render :new
    end
  end

  def edit; end

  def update
    @component_recipes.update(set_params)
    if @component_recipes.save
      redirect_to Component_recipes_path(@component_recipes)
    else
      render :edit
    end
  end

  def destroy
    @component_recipes.destroy
    redirect_to Component_recipess_path
  end

  private
  def set_params
    params.require(:Component_recipes).permit!
  end

  def set_component_recipes
    @component_recipes = ComponentRecipe.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/ramen_recipes_controller.rb
class RamenRecipesController < ApplicationController
  before_action :set_params, only: %i[create update]
  before_action :set_ramen_recipe, only: %i[show edit update destroy]

  def index
    @recipes = RamenRecipe.all + ComponentRecipe.all
  end

  def show
  end

  def new
    @ramen_recipe = RamenRecipe.new
  end

  def create
    @ramen_recipe = RamenRecipe.new(set_params)
    @ramen_recipe.user = current_user
    if @ramen_recipe.save
      redirect_to ramen_recipe_path(@ramen_recipe)
    else
      render :new
    end
  end

  def edit; end

  def update
    @ramen_recipe.update(set_params)
    if @ramen_recipe.save
      redirect_to ramen_recipe_path(@ramen_recipe)
    else
      render :edit
    end
  end

  def destroy
    @ramen_recipe.destroy
    redirect_to ramen_recipes_path
  end

  private
  def set_params
    params.require(:ramen_recipe).permit!
  end

  def set_ramen_recipe
    @ramen_recipe = RamenRecipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <h1>Discover Ramen</h1>
  <%= simple_form_for :search, url: root_path, method: :get do |f| %>
    <div class="search-form-control form-group">
      <input class="form-control string required" type="text" name="search[query]" id="search_query" />
      <button name="button" type="submit" class="btn btn-flat">
        <i class="fas fa-search"></i> Search
      </button>
    </div>
  <% end %>

  <p>CTA to search or create recipes</p>
  <%= link_to "index", ramen_recipes_path%>
  <%= link_to "create", new_ramen_recipe_path%>
</div>

app/views/ramen_recipes/_form.html.erb
<%=  simple_form_for(ramen_recipe) do |f| %>
  <div class="d-flex">
    <%=  f.input :name, wrapper_html: {class: "margin-r"}%>
    <%=  f.input :ramen_type, collection: ["Shio", "Shoyu", "Miso", "Tonkotsu"], wrapper_html: {class: "margin-l"}%>
  </div>
  <%=  f.input :description %>
  <%=  f.input :assembly %>
  <%=  f.input :image %>
  <%= f.submit "Create Recipe",  class: "yellow-btn" %>
<% end %>

app/views/ramen_recipes/edit.html.erb
<%=  render 'form', ramen_recipe: @ramen_recipe %>

app/views/ramen_recipes/index.html.erb
<div class="container">
  <% unless @recipes.empty? %>
    <p>Ramen Recipes<p>
  <% else %>
    <p>There aren't any recipes here.</p>
  <% end %>

  <div class="recipe-container">
    <% @recipes.each do |recipe| %>
      <% if recipe.is_a?(RamenRecipe) %>
        <li>
          <%= link_to recipe.name, ramen_recipe_path(recipe) %>
          <%= link_to "edit", edit_ramen_recipe_path(recipe)%>
          <%= link_to "delete", ramen_recipe_path(recipe), method: :delete%>
        </li>
      <% elsif recipe.is_a?(ComponentRecipe) %>
        <li>
          <%= link_to "#{recipe.name} #{recipe.component}", component_recipe_path(recipe) %>
          <%= link_to "edit", edit_component_recipe_path(recipe)%>
          <%= link_to "delete", component_recipe_path(recipe), method: :delete%>
        </li>
      <% else %>
        <% next %>
      <% end %>
    <% end %>
  </div>

app/views/ramen_recipes/new.html.erb
<%=  render 'form', ramen_recipe: @ramen_recipe %>

app/views/ramen_recipes/show.html.erb
<h1><%= @ramen_recipe.name %></h1>
<div class="info">
  <%= @ramen_recipe.ramen_type %>
  <%= @ramen_recipe.user_id %>
  <%= @ramen_recipe.created_at %>
</div>

<div class="instructions">
  <h2>Description</h2>
  <p> <%= @ramen_recipe.description %></p>
  <% @ramen_recipe.component_recipes.each do |component| %>
  <p><%= component.component %></p>
  <p><%= component.name %></p>
  <p><%= component.description %></p>
  <p><%= component.ingredients %></p>
  <p><%= component.directions %></p>
  <p><%= component.user_id %></p>
  <% end %>
  <p><%= @ramen_recipe.assembly %><p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Messages", "#", class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>